### ISSUE TITLE
exception: cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by hmoffatt** [evolv-ai/serverless-offline-edge-lambda#6]
I am getting the following exception starting offline with the plugin installed. It looks like I need to define custom.offlineEdgeLambda.path even though I don't need it. I am using the nodejs10.x runtime.

`TypeError: Cannot read property 'path' of undefined
    at new BehaviorRouter (/home/hamish/.../node_modules/serverless-offline-edge-lambda/dist/behavior-router.js:53:70)
    at new OfflineEdgeLambdaPlugin (/home/hamish/.../node_modules/serverless-offline-edge-lambda/dist/index.js:16:23)
    at PluginManager.addPlugin (/home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/lib/classes/PluginManager.js:64:28)
    at plugins.forEach.plugin (/home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/lib/classes/PluginManager.js:106:14)
    at Array.forEach (<anonymous>)
    at PluginManager.loadPlugins (/home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/lib/classes/PluginManager.js:100:13)
    at PluginManager.loadServicePlugins (/home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/lib/classes/PluginManager.js:154:10)
    at PluginManager.loadAllPlugins (/home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/lib/classes/PluginManager.js:95:10)
    at pluginManager.loadConfigFile.then.then (/home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/lib/Serverless.js:78:28)
From previous event:
    at Serverless.init (/home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/lib/Serverless.js:76:8)
    at initializeErrorReporter.then (/home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/bin/serverless.js:43:10)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at /home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/bin/serverless.js:30:6
    at Object.<anonymous> (/home/hamish/.nodenv/versions/10.15.3/lib/node_modules/serverless/bin/serverless.js:71:7)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
`

**Comment by choonge** [comment]
This does not seem to apply to the 1.0.2 release. Can we get a new release with this fix?

**Comment by vanhumbeecka** [comment]
Still broken

**Comment by chandywerks** [comment]
I'm also getting this error. I'm using the typescript plugin however setting custom.offlineEdgeLambda.path to '.build' doesn't fix the issue.

**Comment by ryanolee** [comment]
For now created a very "rough" version under `@ryan-o-lee/serverless-offline-edge-lambda` until such a time a v1.0.3 is given on the main repo just to get things working :thinking:

**Comment by ryanolee** [comment]
Hi @matthewstrom @mattstrom,
Thanks for all the work you have put into this package :rocket:.
Do you know if there would be any chance of getting a new version released from master considering 1.0.2 seems to be having some problems a fair few problems? :pray:

**Comment by ryanolee** [comment]
New release is here! 🚀 This should in theory be resolved now 🎉 Thanks Matthew!

**Comment by ryanolee** [comment]
Hi @matthewstrom @mattstrom,
I think this issue can be probably closed (tested and confirmed this one was working on my end) :+1:
